export const mockUsers = [
  {
    id: "user-001",
    name: "Admin Utama",
    email: "admin@laundry.com",
    role: "superadmin" as const,
    banned: false,
    createdAt: "2025-01-01T10:00:00",
  },
  {
    id: "user-002",
    name: "Taufik Hidayat",
    email: "taufik@laundry.com",
    role: "admin" as const,
    banned: false,
    createdAt: "2025-01-05T10:00:00",
  },
  {
    id: "user-003",
    name: "Siti Nurhaliza",
    email: "siti@laundry.com",
    role: "admin" as const,
    banned: false,
    createdAt: "2025-01-10T10:00:00",
  },
  {
    id: "user-004",
    name: "Budi Santoso",
    email: "budi@laundry.com",
    role: "user" as const,
    banned: false,
    createdAt: "2025-02-01T10:00:00",
  },
  {
    id: "user-005",
    name: "Ani Wijaya",
    email: "ani@laundry.com",
    role: "user" as const,
    banned: true,
    createdAt: "2025-02-05T10:00:00",
  },
  {
    id: "user-006",
    name: "Rudi Gunawan",
    email: "rudi@laundry.com",
    role: "user" as const,
    banned: false,
    createdAt: "2025-02-10T10:00:00",
  },
];
